In [3]:
import pandas as pd

In [4]:
data = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/6_train_test_split/carprices.csv")
data.head()

   Mileage  Age(yrs)  Sell Price($)
0    69000         6          18000
1    35000         3          34000
2    57000         5          26100
3    22500         2          40000
4    46000         4          31500

In [6]:
x = data[['Mileage', 'Age(yrs)']]
x.head()

   Mileage  Age(yrs)
0    69000         6
1    35000         3
2    57000         5
3    22500         2
4    46000         4

In [7]:
y = data[['Sell Price($)']]
y.head()

   Sell Price($)
0          18000
1          34000
2          26100
3          40000
4          31500

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_tr, x_t, y_tr, y_t = train_test_split(x,y,test_size=0.2)

In [14]:
len(x_tr)

16

In [15]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [16]:
lr.fit(x_tr, y_tr)

LinearRegression()

In [17]:
lr.predict(x_t)

array([[30185.75226569],
       [15158.65839915],
       [20822.16537585],
       [16851.92576038]])

In [19]:
lr.score(x_t,y_t)

0.9295860588676126

In [20]:
y_t.head()

    Sell Price($)
4           31500
18          12800
7           19300
10          18700